### ISSUE TITLE
What things does the sensor part measure?

### ISSUE THREAD

**Issue by justinclift** [breiler/soilops#7]
Interesting project idea.  "Soil sensor monitoring server".

What are the things currently measured?

Asking just because I've been helping out a friend's agriculture robotics startup.  So sounds like a sort-of-related topic. :smile:

**Comment by breiler** [comment]
It is collecting light, temperature and moisture and just plots the data in a graph. It wouldn't be hard to change the data model to be more dynamic to store any data you'd like.

We have focused on the registration part of an iot device, tying to make the process safe, simple and secure in a multi tenant environment.

We have a server up and running which you could try out. Just need to find it's url and I can get back to you.

The development has halted a bit since corona and I'm not sure when we can pick it up again. If you find any code useful just grab it! ;)

**Comment by justinclift** [comment]
No worries. :smile:

The friends startup is doing everything on AWS, so they'd probably go with sending the info to AWS IoT via MQTT for storage/redistribution of the data to whatever needs it from there.  So far (!) that seems to work ok. :shrug:

**Comment by breiler** [comment]
Ah, we started looking at AWS, but I didn't want to depend on a cloud solution. Are you guys documenting the progress of the project somewhere?

**Comment by justinclift** [comment]
Not yet.  It's still at the stage of "get the initial prototype working".  Seems about 80% of the way there (rough guess). :smile:

**Comment by justinclift** [comment]
Oops, forgot to close this. :wink:
